name: daqviewer
channels:
  - defaults
  - conda-forge
dependencies:
  - pip==21.3.1
  - python==3.9.2
  - pip:
    - setuptools==60.2.0
    - wheel==0.37.1
    - pglive-0.7.6
    - pyqtdarktheme-2.1.0
    - QLed-1.3.1
    - PyQt5-5.15.11
    - python-osc-1.8.3
    # - pyOSC3-1.2
    # - osc4py3-1.0.8
    - defopt
    - pyyaml